# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
EXPOSE 1400
WORKDIR /app

ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS="http://*:1400"

# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["GameStore.API.OData/GameStore.API.OData.csproj", "GameStore.API.OData/"]
COPY ["GameMarketPlace/Business/Business.csproj", "GameMarketPlace/Business/"]
COPY ["Models/Models.csproj", "Models/"]
COPY ["GameMarketPlace/Core/Core.csproj", "GameMarketPlace/Core/"]
COPY ["GameMarketPlace/Entities/Entities.csproj", "GameMarketPlace/Entities/"]
COPY ["GameMarketPlace/Configuration/Configuration.csproj", "GameMarketPlace/Configuration/"]
COPY ["GameMarketPlace/DataAccess/DataAccess.csproj", "GameMarketPlace/DataAccess/"]
COPY ["GameMarketPlace/MeArch.Module.Security/MeArch.Module.Security.csproj", "GameMarketPlace/MeArch.Module.Security/"]
RUN dotnet restore "./GameStore.API.OData/GameStore.API.OData.csproj"
COPY . .
WORKDIR "/src/GameStore.API.OData"
RUN dotnet build "./GameStore.API.OData.csproj" -c $BUILD_CONFIGURATION -o /app/build

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./GameStore.API.OData.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "GameStore.API.OData.dll"]