version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: gamestore.db.sql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    networks:
      - appnet

  webapi:
    build:
      context: .
      dockerfile: dockerfile-webapi
    container_name: gamestore.api.web
    ports:
      - "1453:1453"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://*:1453"
    depends_on:
      - db
    networks:
      - appnet

  odataapi:
    build:
      context: .
      dockerfile: dockerfile-odatapi
    container_name: gamestore.api.odata
    ports:
      - "1071:1400"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://*:1400"
    depends_on:
      - db
    networks:
      - appnet

networks:
  appnet:
    driver: bridge