FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
EXPOSE 1453
EXPOSE 1071
WORKDIR /app

ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS="http://*:1453;https://*:1071"

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
ARG BUILD_CONFIGURATION=Release

WORKDIR /src
COPY ["GameStore.API.Web/GameStore.API.Web.csproj", "GameStore.API.Web/"]
COPY ["GameMarketPlace/Business/Business.csproj", "GameMarketPlace/Business/"]
COPY ["Models/Models.csproj", "Models/"]
COPY ["GameMarketPlace/Core/Core.csproj", "GameMarketPlace/Core/"]
COPY ["GameMarketPlace/Entities/Entities.csproj", "GameMarketPlace/Entities/"]
COPY ["GameMarketPlace/Configuration/Configuration.csproj", "GameMarketPlace/Configuration/"]
COPY ["GameMarketPlace/DataAccess/DataAccess.csproj", "GameMarketPlace/DataAccess/"]
COPY ["GameMarketPlace/MeArch.Module.Security/MeArch.Module.Security.csproj", "GameMarketPlace/MeArch.Module.Security/"]
RUN dotnet restore "./GameStore.API.Web/GameStore.API.Web.csproj"
COPY . .
WORKDIR "/src/GameStore.API.Web"
RUN dotnet build "./GameStore.API.Web.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./GameStore.API.Web.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "GameStore.API.Web.dll"]