services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: gamestore.db.sql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    networks:
      - appnet
    volumes:
      - sql_data:/var/opt/mssql

networks:
  appnet:
    external: true

volumes:
  sql_data: