services:
  rabbitmq:
    image: rabbitmq:management
    container_name: gamestore.rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=gamestore
      - RABBITMQ_DEFAULT_PASS=gamestore
    networks:
      - appnet

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: gamestore.db.sql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    networks:
      - appnet
    volumes:
      - sql_data:/var/opt/mssql

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: gamestore.db.mongodb
    ports:
      - "27000:27017"
    networks:
      - appnet
    volumes:
      - mongo_data:/data/db

  webapi:
    image: developergeralt/gamestore.api.web
    container_name: gamestore.api.web
    ports:
      - "1453:1453"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://*:1453"
    depends_on:
      - db
      - rabbitmq
    networks:
      - appnet

  odataapi:
    image: developergeralt/gamestore.api.odata
    container_name: gamestore.api.odata
    ports:
      - "1071:1400"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://*:1400"
    depends_on:
      - db
      - rabbitmq
    networks:
      - appnet

  
  metaapi:
    image: developergeralt/gamestore.api.meta
    container_name: gamestore.api.meta
    ports:
      - "2016:2016"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://*:2016"
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  sql_data:
  mongo_data:
